"'SHS Configuration' As screen":

    SHSConfigComp As Component1:
        CurrentScreen: ="Configuration"
        Height: =768

    CanVasContainer_16 As groupContainer.manualLayoutContainer:
        Height: =App.Height-Component1_1.ComHeaderHeight
        Width: =App.Width-Component1_1.VarMenuWidth
        X: =SHSConfigComp.VarMenuWidth
        Y: =Component1_1.ComHeaderHeight
        ZIndex: =7

    "'SHSConfig Main' As groupContainer.verticalAutoLayoutContainer":
        Height: =App.Height-SHSConfigComp.ComHeaderHeight
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =App.Width-SHSConfigComp.VarMenuWidth
        X: =SHSConfigComp.VarMenuWidth
        Y: =SHSConfigComp.ComHeaderHeight
        ZIndex: =8

        Label13 As label:
            Color: =RGBA(0, 18, 107, 1)
            FontWeight: =FontWeight.Bold
            Height: =50
            Size: =20
            Text: ="Supplier Happiness Survey Settings"
            Width: =550
            X: =52
            Y: =2
            ZIndex: =1

        Container40 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.None
            FillPortions: =0
            Height: =30
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =3

            Container40_1 As groupContainer.horizontalAutoLayoutContainer:
                DropShadow: =DropShadow.None
                Height: =10
                LayoutMinHeight: =10
                LayoutMinWidth: =900
                LayoutMode: =LayoutMode.Auto
                Width: =900
                ZIndex: =2

                Icon13 As icon.HorizontalLine:
                    BorderColor: =RGBA(102, 102, 102, 1)
                    BorderThickness: =1
                    Color: =RGBA(102, 102, 102, 1)
                    FillPortions: =1
                    Height: =3
                    Icon: =Icon.HorizontalLine
                    PaddingBottom: =10
                    PaddingLeft: =10
                    PaddingRight: =10
                    PaddingTop: =10
                    Width: =1039
                    X: =52
                    Y: =60
                    ZIndex: =2

            Container40_2 As groupContainer.horizontalAutoLayoutContainer:
                DropShadow: =DropShadow.None
                FillPortions: =0
                Height: =20
                LayoutMinHeight: =10
                LayoutMinWidth: =150
                LayoutMode: =LayoutMode.Auto
                Width: =200
                ZIndex: =3

        Container41 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.None
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =4

            Container42 As groupContainer.verticalAutoLayoutContainer:
                DropShadow: =DropShadow.None
                FillPortions: =0
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                Width: =80
                ZIndex: =1

            Container42_1 As groupContainer.verticalAutoLayoutContainer:
                DropShadow: =DropShadow.None
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =550
                LayoutMode: =LayoutMode.Auto
                ZIndex: =2

                Container43 As groupContainer.verticalAutoLayoutContainer:
                    BorderThickness: =2
                    DropShadow: =DropShadow.Bold
                    FillPortions: =0
                    Height: =500
                    LayoutDirection: =LayoutDirection.Vertical
                    LayoutMinHeight: =100
                    LayoutMinWidth: =550
                    LayoutMode: =LayoutMode.Auto
                    RadiusBottomLeft: =20
                    RadiusBottomRight: =20
                    RadiusTopLeft: =20
                    RadiusTopRight: =20
                    ZIndex: =1

                    Label31 As label:
                        Fill: =RGBA(214, 221, 224, 1)
                        FontWeight: =FontWeight.Bold
                        Height: =50
                        Size: =18
                        Text: ="  Edit Configuration"
                        Width: =Parent.Width
                        ZIndex: =1

                    Label36 As label:
                        FontWeight: =FontWeight.Semibold
                        Text: |-
                            ="   Stakeholder : Supplier"
                        Width: =350
                        ZIndex: =2

                    Container45 As groupContainer.horizontalAutoLayoutContainer:
                        DropShadow: =DropShadow.None
                        FillPortions: =0
                        Height: =40
                        LayoutJustifyContent: =LayoutJustifyContent.Center
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        ZIndex: =4

                        Icon29 As icon.HorizontalLine:
                            Color: =RGBA(214, 221, 224, 1)
                            Fill: =RGBA(214, 221, 224, 1)
                            Height: =2
                            Icon: =Icon.HorizontalLine
                            Width: =550
                            ZIndex: =1

                    Container42_2 As groupContainer.verticalAutoLayoutContainer:
                        DropShadow: =DropShadow.None
                        FillPortions: =0
                        Height: =40
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        Width: =60
                        ZIndex: =6

                        Label36_5 As label:
                            Align: =Align.Right
                            FontWeight: =FontWeight.Semibold
                            Text: ="    Current Year"
                            ZIndex: =1

                        Label36_6 As label:
                            Color: =RGBA(255, 0, 0, 1)
                            FontWeight: =FontWeight.Bold
                            PaddingLeft: =0
                            Text: ="*"
                            Width: =117
                            ZIndex: =2

                    Container42_4 As groupContainer.verticalAutoLayoutContainer:
                        DropShadow: =DropShadow.None
                        FillPortions: =0
                        Height: =40
                        LayoutAlignItems: =LayoutAlignItems.Center
                        LayoutGap: =40
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        Width: =60
                        ZIndex: =7

                        Label36_7 As label:
                            Color: =RGBA(255, 0, 0, 1)
                            FontWeight: =FontWeight.Bold
                            PaddingLeft: =0
                            Text: ="    "
                            Width: =10
                            ZIndex: =1

                        TextInput1 As text:
                            Default: ="Text input"
                            ZIndex: =2

                        Button17 As button:
                            Height: =35
                            Text: ="Button"
                            ZIndex: =3

            Container42_3 As groupContainer.verticalAutoLayoutContainer:
                DropShadow: =DropShadow.None
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                ZIndex: =4

                Container44 As groupContainer.verticalAutoLayoutContainer:
                    AlignInContainer: =AlignInContainer.SetByContainer
                    BorderThickness: =2
                    DropShadow: =DropShadow.Bold
                    FillPortions: =0
                    Height: =300
                    LayoutDirection: =LayoutDirection.Vertical
                    LayoutMinHeight: =100
                    LayoutMinWidth: =250
                    LayoutMode: =LayoutMode.Auto
                    RadiusBottomLeft: =20
                    RadiusBottomRight: =20
                    RadiusTopLeft: =20
                    RadiusTopRight: =20
                    Width: =400
                    ZIndex: =1

                    Label31_1 As label:
                        Fill: =RGBA(214, 221, 224, 1)
                        FontWeight: =FontWeight.Bold
                        Height: =50
                        Size: =18
                        Text: ="  Existing Configuration"
                        Width: =Parent.Width
                        ZIndex: =1

                    Label36_4 As label:
                        FontWeight: =FontWeight.Semibold
                        Text: |-
                            ="Stakeholder : Supplier"
                        Width: =350
                        ZIndex: =2

                    Container45_1 As groupContainer.horizontalAutoLayoutContainer:
                        DropShadow: =DropShadow.None
                        FillPortions: =0
                        Height: =40
                        LayoutJustifyContent: =LayoutJustifyContent.Center
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        ZIndex: =3

                        Icon29_2 As icon.HorizontalLine:
                            Color: =RGBA(214, 221, 224, 1)
                            Fill: =RGBA(214, 221, 224, 1)
                            Height: =2
                            Icon: =Icon.HorizontalLine
                            Width: =350
                            ZIndex: =1

    Container45_2 As groupContainer.horizontalAutoLayoutContainer:
        DropShadow: =DropShadow.None
        Height: =40
        LayoutJustifyContent: =LayoutJustifyContent.Center
        LayoutMode: =LayoutMode.Auto
        X: =20
        Y: =110
        ZIndex: =9

        Icon29_3 As icon.HorizontalLine:
            Color: =RGBA(214, 221, 224, 1)
            Fill: =RGBA(214, 221, 224, 1)
            Height: =2
            Icon: =Icon.HorizontalLine
            Width: =350
            ZIndex: =1

